export type ThemeData = {
  isDark: boolean;
  primaryColor: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  onPrimary: string;
  secondaryColor: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  onSecondary: string;
  tertiaryColor: string;
  tertiaryContainer: string;
  backgroungColor: string;
  surfaceVariant: string;
  onSurfaceVariant: string;
  shadowColor: string;
  disabledBtnColor: string;
  whiteInverse: string;
  blackInverse: string;
  borderColor: string;
};
